version: '3.8'

services:
  web:
    image: leolazz/2bdone:test
    build: .
    ports:
      - '3000:80'
    volumes:
      - type: bind
        source: ./src/DB
        target: /db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
