version: "3.8"

services:
    web:
      build: .
      ports: 
        - "5000:80"
      volumes:
        - C:\Users\Leo\source\repos\Personal\ToDoList\sqlitetodolist.db:/ToDoList/
      environment:
        - Development

