version: "3.8"

services:
    web:
      image: leolazz/2bdone:latest
      build: .
      ports: 
        - "5000:80"
      volumes:
        - type: bind
          source: .\DB
          target: /ToDoList/DB/
      environment:
        - FACEBOOK_APPID=
        - FACEBOOK_APPSECRET=
        - ASPNETCORE_ENVIRONMENT=Production

