version: "3.8"

services:
    web:
      build: .
      ports: 
        - "5000:80"
      volumes:
        - type: bind
          source: .\DB
          target: /ToDoList/DB/
      environment:
        - Development

