name: ToDoList .Net

on:
  push:
    branches:  
    - main 
    - '**'
  pull_request:
    branches: 
    - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./

    - name: Build
      run: dotnet build ToDoList.sln --no-restore
      working-directory: ./

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: leolazz/2bedone
          tag_with_ref: true
